[phases.setup]
nixPkgs = [
  "nodejs_20",
  "npm-9_x",
  "libnss3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libgbm1",
  "libasound2",
  "libpangocairo-1.0-0",
  "libxss1",
  "libgtk-3-0",
  "libxshmfence1",
  "libglu1",
  "google-chrome-stable"
]

[phases.install]
cmds = ["npm ci"]

[start]
cmd = "node app.js"
