[phases.setup]
aptPkgs = [
  "libnss3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libgbm1",
  "libasound2",
  "libpangocairo-1.0-0",
  "libxss1",
  "libgtk-3-0",
  "libxshmfence1",
  "libglu1"
]

[phases.install]
cmds = [
  "wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb",
  "apt-get update",
  "apt-get install -y ./google-chrome-stable_current_amd64.deb",
  "rm google-chrome-stable_current_amd64.deb",
  "npm ci"
]

[start]
cmd = "node app.js"
